name: dotnet-blazor-base

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build image
  jobs:

  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Docker@2
      displayName: Build the docker image
      inputs:
        command: buildAndPush
        containerRegistry: dockerHub
        repository: thbst16/dotnet-blazor-base
        tags: |
          $(Build.BuildId)
          latest